import Head from "next/head";
import Header from "./components/layouts/Header";
import Hero from "./components/sections/Hero";
import Achievements from "./components/sections/Achievements";
import Aboutus from "./components/sections/Aboutus";
import Products from "./components/sections/Products";
import Testimonials from "./components/sections/Testimonials";
import Footer from "./components/layouts/Footer";
import Cart from "./components/sections/Cart";

export default function Home({ cart, setCart, session }) {
  return (
    <>
      <Head>
        <title>Super Alts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header activeLink={"home"} />
      <Cart cart={cart} setCart={setCart} session={session} />
      <Hero />
      <Achievements />
      <Aboutus />
      <Products cart={cart} setCart={setCart} />
      <Testimonials />
      <Footer />
    </>
  );
}
